### ISSUE TITLE
Donations URL Language

### ISSUE THREAD

**Issue by Scrxtchy** [dasmikko/facepunchdroid#1]
for the sake of dominance in language and facepunch's userbase  
I noticed that Donate button was removed from the menu, but is still in the code (and gives a error because the Resource doesn't exist in menu xml
The webpage loads in Danish, which may be too confusing for the masses
The fix I found to be to change the default location to anything english, USA, UK etc.

If it's ever considered to be implemented back in, I'd suggest using
`lc=US` instead of `lc=DK`
If the user lives in a different country, the page will load their language when they chose it from the combo box in paypal (or login)

**Comment by dasmikko** [comment]
That URL was for when the app was on Amazon Appstore, because of Google Play policy, all iAPS or donations has to go thourgh Google Play
