### ISSUE TITLE
Custom CSS file is not applied

### ISSUE THREAD

**Issue by Scrxtchy** [dasmikko/facepunchdroid#11]
I have a file called x.css in the root of my SD card, the file point is pointing to it, and the switch is turned on, however with no attempt at the current state of code was I able to apply a custom file

```
                    if(useCustomStyles) {
                        if(sharedPref.contains("custom_style_file")) {
                            String filePath = sharedPref.getString("custom_style_file", "");
                            Log.d("CUSTOM CSS", String.valueOf(Uri.parse(filePath)));
                            String userCustomCSS = customCSS.readFromSDcard(sharedPref.getString("custom_style_file", ""));
                            String injectUserCSS = "javascript:var css=\"" + userCustomCSS + "\",head=document.head;style=document.createElement(\"style\"),style.type=\"text/css\",style.appendChild(document.createTextNode(css)),head.appendChild(style);";
                            Log.d("Injected css", injectUserCSS);
                            view.loadUrl(injectUserCSS);
                        }

                    }
```

Stepping through the debugger, I hit True with the useCustomStyles, but I do not pass sharedPref.contains("custom_style_file")
Looking at the XML prefs. file I can see why this is happening

```
<?xml version='1.0' encoding='utf-8' standalone='yes' ?>
<map>
    <boolean name="enable_custom_styles" value="true" />
</map>
root@hammerhead:/ #
```

**Comment by dasmikko** [comment]
The XML part is for setting the default value, but I have to test it some more.

**Comment by dasmikko** [comment]
Can you post the CSS you try to use?

**Comment by Scrxtchy** [comment]
I was using this
https://userstyles.org/styles/115525/facepunch-awfully-dark

**Comment by dasmikko** [comment]
Make sure you escape all quotes like so:

**Before:**
`content: " x ";`

**After:**
`content: \" x \";`

If you don't it will break the Javascript that is used to inject the CSS.

Maybe we should have a method to auto escape the quotes, to make life easier.

**Comment by dasmikko** [comment]
Did it solve it?
