### ISSUE TITLE
Unable to quickly access PMs in app

### ISSUE THREAD

**Issue by UnixNight** [dasmikko/facepunchdroid#12]
There is no quick way to view private messages in the app. If I find my way to the page for PMs, everything is scrunched to the side of the page due to the user settings and inbox tabs. Messages are unreadable. Currently running on an LG G4 H812 with Android 6.0

**Comment by dasmikko** [comment]
CSS is also updated in this commit: 537a71fa61a21f655ff5423f8951241c24468328
