### ISSUE TITLE
Pull down to refresh 

### ISSUE THREAD

**Issue by JustaPeriod** [dasmikko/facepunchdroid#15]
Commonly seen in apps, especially apps with material design, pulling down from the top of a window lets you refresh. Currently you can't drag from the top of the page to refresh. 

http://imgur.com/UWrUEFp

**Comment by dasmikko** [comment]
Thanks for reminding me on this. I have been thinking about implementing this, but forgot to write it down. :v:

Shouldn't be too hard to implement
