### ISSUE TITLE
Testing that UA works with new facepunch icon

### ISSUE THREAD

**Issue by dasmikko** [dasmikko/facepunchdroid#16]
I'm having a little trouble testing, that the UA icon for Facepunch works.

It seems to work with my phone, but I'm unsure if it works with other phones.

Could someone help me test this?
And if yes, use the latest version from Google Play v1.3.3

**Comment by UnixNight** [comment]
Working on my LG G4

[post 1](https://facepunch.com/showthread.php?t=1511218&p=49983564&highlight=#post49983564)
[post 2](https://facepunch.com/showthread.php?t=1510395&p=49983663&highlight=#post49983663)

**Comment by dasmikko** [comment]
Awesome, is the post editor in the bottom working too? Because, im experincing some issues there too.

**Comment by UnixNight** [comment]
if you mean the quick reply box, it seems to work fine. I don't see any issues other than that there is no autocorrect when im typing.

**Comment by dasmikko** [comment]
Hmm, that's weird.. The autocorrect thing i believe is normal.

**Comment by UnixNight** [comment]
It does this with both Google Keyboard and LG Keyboard. Autocorrect is not working

**Comment by dasmikko** [comment]
I can't seem to replicate this problem.

**Comment by UnixNight** [comment]
Here is what happens on my phone

[video](https://drive.google.com/open?id=0B-UpzvBwI7R-MXlTdGRLTm5NaG8)

**Comment by dasmikko** [comment]
Try that.

**Comment by UnixNight** [comment]
Still nothing. No autocorrect

**Comment by dasmikko** [comment]
I have spend a small hour on the topic, and simply can't find any information on it. If more users has this problem, then I will reopen this issue.
