### ISSUE TITLE
Support for 4.2.2

### ISSUE THREAD

**Issue by ghost** [dasmikko/facepunchdroid#2]
My device which is a Huawei Y320-U10 is stuck on 4.2.2. Would be nice to have support for 4.2.X devices.

**Comment by dasmikko** [comment]
I have done some testing, and there seems be be some issues with injecting the custom CSS/JS.
I believe it's because it doesn't use the Chrome WebView that was implemented in KitKat+

**Comment by ghost** [comment]
Darn.
Aight thanks for trying anyway.
