### ISSUE TITLE
Quoted imgur albums fucks up the page. 

### ISSUE THREAD

**Issue by hallowieners** [dasmikko/facepunchdroid#32]
It can extend out of the quote box and the post elements. It also increased the page's width so I was able to scroll horizontally. 
![screenshot_20160328-100520](https://cloud.githubusercontent.com/assets/11741609/14086942/9f0414c6-f4f5-11e5-9d14-53f9f8cf6205.png)

**Comment by dasmikko** [comment]
Can I have a link to the thread? It's helps a lot.

**Comment by hallowieners** [comment]
https://facepunch.com/showthread.php?t=1509953&p=50016824&viewfull=1#post50016824
