### ISSUE TITLE
Long thread titles break things! 

### ISSUE THREAD

**Issue by hallowieners** [dasmikko/facepunchdroid#4]
Threads with long titles sort of flow out of the white top area. 

There's also another issue where the page count bar seems to be busted in this particular thread but other threads with long titles don't seem to break the page count bar. 

On Nexus 5 (2013) running 6.0.1 

![screenshot_20160319-214709](https://cloud.githubusercontent.com/assets/11741609/13902773/843f59de-ee2e-11e5-8585-b3fc88d280f1.png)

**Comment by dasmikko** [comment]
FIxed in this commit `e2d0b3a`
