### ISSUE TITLE
Page selector only show scrollbar when there is enough space

### ISSUE THREAD

**Issue by SuperHighVoltage** [dasmikko/facepunchdroid#45]
And not when there is too many pages

**Comment by dasmikko** [comment]
Do you have an example?

**Comment by SuperHighVoltage** [comment]
Do you want pictures or threads?

**Comment by dasmikko** [comment]
Both if possible.

**Comment by SuperHighVoltage** [comment]
https://www.dropbox.com/s/izzzcawcax23iif/Screenshot_2016-04-11-07-35-24.png?dl=0
https://www.dropbox.com/s/ssvc38hq1zotf9f/Screenshot_2016-04-11-07-35-51.png?dl=0

**Comment by dasmikko** [comment]
I'm planning to implement a native pager, so we won't have to deal the HTML pagination.
