### ISSUE TITLE
News node articles open in thread instead of opening page

### ISSUE THREAD

**Issue by SuperHighVoltage** [dasmikko/facepunchdroid#48]
Not sure if this is an issue with embedly or not but when you press "read article on whatever.com" it renders the article in the thread itself

https://www.dropbox.com/s/ai2yzryhbjtuqpm/Screenshot_2016-04-13-14-12-06.png?dl=0

**Comment by dasmikko** [comment]
Looks like an issue with embedly, but I can probably do some Javascript magic.

**Comment by dasmikko** [comment]
Did some testing, and can't seem to fix it, because of embedly.
