### ISSUE TITLE
Allow popular/read/ticker/mail/options icons to stay on the top of the page

### ISSUE THREAD

**Issue by AkujiTheSniper** [dasmikko/facepunchdroid#51]
Basically leave them where they would be relative to where they are on the desktop site. Maybe make them look how the ratings look (from left to right on one line, centered)

**Comment by dasmikko** [comment]
I have thought a lot about this, and done some testing and decided not to implement a function.
The reason for this, is that it's more easily solved by using a custom css style.
The other reason is that, you are supposed to use the navigation drawer to go to the different pages

If I have to make a switch or a toggle for every little thing on the forum, the settings will end up getting very cluttered and confused, and the code will end up cluttered too.

Here is the CSS to fix this:

```
#navbarlinks { margin: 20px 5%; }
#navbarlinks, #navbarlinks div {
    display: block !important;
}
```

I hope this is a good enough solution for you.
