### ISSUE TITLE
Navigation bar on "read threads" page

### ISSUE THREAD

**Issue by SuperHighVoltage** [dasmikko/facepunchdroid#54]
It also crashes app when you try changing the page when you shouldn't be able to, like when on the read threads page

**Comment by dasmikko** [comment]
I can't seem to reproduce the bug, how are you producing the bug?

**Comment by SuperHighVoltage** [comment]
It's not happening now, weird. Must of been an random bug, it did happen when again when it was doing the cloud fire thing and I was able to crash it when trying to change the page there

**Comment by dasmikko** [comment]
Okay then, I will close the issue, and if more people report happen, or I experience it, I will reopen it.
