### ISSUE TITLE
native pagination always appears on app start

### ISSUE THREAD

**Issue by Scrxtchy** [dasmikko/facepunchdroid#55]
this is when the application loads to the forum frontpage, which doesn't use pagination
pressing a button crashes application

**Comment by dasmikko** [comment]
Can you try and check if there is an update on Google Play? 

I pushed several updates today, regarding this issue. And I can't replicate this issue.

**Comment by Scrxtchy** [comment]
I'm running dc4f9e4

**Comment by dasmikko** [comment]
That is weird.. 

If it isn't too much to ask of, can you post an image or even a video of the bug?

**Comment by Scrxtchy** [comment]
https://www.youtube.com/watch?v=V0f-A1O8rf4

**Comment by dasmikko** [comment]
Hmm... What error does it throw?

**Comment by Scrxtchy** [comment]
```
04-20 01:07:06.795 15455-15455/com.apps.anker.facepunchdroid E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.apps.anker.facepunchdroid, PID: 15455
                                                                               java.lang.NullPointerException
                                                                                   at com.apps.anker.facepunchdroid.MainActivity$10.onMenuItemClick(MainActivity.java:784)
```

https://github.com/dasmikko/facepunchdroid/blob/master/app/src/main/java/com/apps/anker/facepunchdroid/MainActivity.java#L784

**Comment by dasmikko** [comment]
Try pull my latest commit
ff90dff523a9b702c1cf05f52e20c6e6933aa336

**Comment by Scrxtchy** [comment]
No improvements
same interface error, same crash results

**Comment by dasmikko** [comment]
Try pull latest again

**Comment by Scrxtchy** [comment]
d91eb04
don't ask
I don't know

but it works

**Comment by dasmikko** [comment]
It makes really good sense actually! It's a very good solution. Thanks for the help!
