### ISSUE TITLE
Images within quotes for not open internally

### ISSUE THREAD

**Issue by Scrxtchy** [dasmikko/facepunchdroid#59]
When opening an image within a quote, the image is opened using an external browser

**Comment by Scrxtchy** [comment]
Hmm, I wouldn't call it an isolated case because it's easily replicated, but it also sometimes works
If I can figure out a pattern, I may updated the title to something more accurate

**Comment by dasmikko** [comment]
I did replicate it, and I suspect it's the timing of adding the click event through jQuery.

Update: After some more testing, I was right, I have to wait for the DOM to load, and if you click on the image before the dom is completely loaded, it wont fire the click event for the native image viewer.

**Comment by dasmikko** [comment]
Closing the issue, as there doesn't seem to be a solution to this.
