### ISSUE TITLE
Wonky symbols on "leaving this site" message

### ISSUE THREAD

**Issue by MellowEdge** [dasmikko/facepunchdroid#95]
http://i.imgur.com/KB4WKaT.png

**Comment by dasmikko** [comment]
I can't replicate the issue on my 3 phones.

What phone/android version/language?

**Comment by MellowEdge** [comment]
I'm using Motorola Moto G4, android version 7.0 (I veryrecently updated from Android 6, actually, probably the reason of the bug), English language

**Comment by dasmikko** [comment]
When you say English, is that app or system language?

**Comment by MellowEdge** [comment]
Both app and system is English, system is UK English

**Comment by dasmikko** [comment]
Well, that is odd. 

I can't for whatever reason replicate that.

Plus, there might not be much I can do about it, since the box is made by the forum, and not the app.

Closing, unless more people experience same issue.
